### ISSUE TITLE
Rolling Window Queries with Granularity In Cube.js

### ISSUE THREAD

**Issue by yatesdev** [cube-js/cube#1736]
**Problem**
I have a data set that I want to keep the actuals (unitsSold) per day, but also maintain a rolling sum to be able to "smooth out" some some calculations, namely how long my inventory will last. If no units were sold on one day, the calculation would instantly spike to infinity otherwise.

My thought was to use the RollingWindow queries, and so my cube schema is defined like so:
```js
cube(`Inventory`, {
  sql: `select * from daily_inventory WHERE report_date <= date_add('day', -1, current_date)`, // don't include data for today
  
  measures: {
   // The actual raw value for the given day
    unitsSold: {
      sql: `units_sold`,
      type: `sum`,
    },

    // The rolling sum of the previous 28 days
    rollingUnitsSold: {
      sql: `units_sold`,
      type: `sum`,
      rollingWindow: {
        trailing: `28 day`,
        offset: "end",
      },
    },
  },
  
  dimensions: {
    reportDate: {
      sql: `cast(${CUBE}.report_date AS timestamp)`,
      type: "time",
    },
    
    unitId: {
      sql: "unit_id",
      type: "string",
    },
    sourceId: {
      sql: "source_id",
      type: "string",
    }
  }
})
```

This appears to work fine when the granularity of the query is `day` , however, when the granularity is `month`, I start to get odd results.

If there is a value within this 28 day window, for example 5 units sold on 12-28-2020. For the month of January 2021, I get 0 returned rather than the 5 units I would expect when my query date range is from 10-01-2020 to 1-6-2021 as 12-28-2020 falls within the 28 day window from 1-6-2020

Example Query
```js
{
  "measures":["Inventory.unitsSold","Inventory.rollingUnitsSold"],
  "timeDimensions":[{
    "dimension":"Inventory.reportDate",
    "dateRange":["2020-10-01T00:00:00.000","2021-01-06T23:59:59.999"],
    "granularity":"month"
  }],
  "order":{"Inventory.reportDate":"asc"},
  "dimensions":["Inventory.sourceId"],
  "filters":[]
}
```

**Comment by igorlukanin** [comment]
Hi @yatesdev 👋 

I think this issue was misclassified as a bug and Cube was actually doing what it's supposed to do. Let me explain:

In your data model, you have a rolling window measure that is set to "look back (`trailing`) `28 days` from the end of the `offset` point, which is the `end` of the time interval".
```js
      rollingWindow: {
        trailing: `28 day`,
        offset: "end",
      },
```

> This appears to work fine when the granularity of the query is day , however, when the granularity is month, I start to get odd results.

So, when you're setting the time dimension granularity to `month`, it means that Cube will use monthly intervals, and look back 28 days from the end of each interval. Obviously, 28 days back from the end of each month are within that very month.

> 5 units sold on 12-28-2020. For the month of January 2021, I get 0 returned rather than the 5 units I would expect when my query date range is from 10-01-2020 to 1-6-2021

For this example. Cube would translate your "January 1, 2021" date to the end of the month (January 31, 2021), and then look back 28 days. Since there's no data for January, the measure would evaluate to 0.

And as I said, this is exactly what should be happening.

---

Please take a look at the following example that illustrates the same idea. Data model:

```yaml
cube(`Inventory`, {
  sql: `
    SELECT 1 AS units_sold, '2020-11-01' AS report_date UNION ALL
    SELECT 1 AS units_sold, '2020-11-11' AS report_date UNION ALL
    SELECT 1 AS units_sold, '2020-11-21' AS report_date UNION ALL

    SELECT 1 AS units_sold, '2020-12-01' AS report_date UNION ALL
    SELECT 1 AS units_sold, '2020-12-11' AS report_date UNION ALL
    SELECT 1 AS units_sold, '2020-12-21' AS report_date UNION ALL
    SELECT 1 AS units_sold, '2020-12-31' AS report_date UNION ALL

    SELECT 1 AS units_sold, '2021-01-01' AS report_date UNION ALL
    SELECT 1 AS units_sold, '2021-01-11' AS report_date UNION ALL
    SELECT 1 AS units_sold, '2021-01-21' AS report_date UNION ALL
    SELECT 1 AS units_sold, '2021-01-31' AS report_date UNION ALL

    SELECT 1 AS units_sold, '2021-02-01' AS report_date UNION ALL
    SELECT 1 AS units_sold, '2021-02-11' AS report_date UNION ALL
    SELECT 1 AS units_sold, '2021-02-21' AS report_date
  `,
  
  measures: {
   // The actual raw value for the given day
    unitsSold: {
      sql: `units_sold`,
      type: `sum`,
    },

    // The rolling sum of the previous 28 days
    rollingUnitsSold: {
      sql: `units_sold`,
      type: `sum`,
      rollingWindow: {
        trailing: `28 day`,
        offset: `end`,
      },
    },
  },
  
  dimensions: {
    reportDate: {
      sql: `cast(${CUBE}.report_date AS timestamp)`,
      type: "time",
    },
    
    unitId: {
      sql: "unit_id",
      type: "string",
    },
    sourceId: {
      sql: "source_id",
      type: "string",
    }
  }
})
```

Query (you can change the granularity to `month` as well):
```json
{
  "measures": [
    "Inventory.unitsSold",
    "Inventory.rollingUnitsSold"
  ],
  "timeDimensions": [
    {
      "dimension": "Inventory.reportDate",
      "dateRange": [
        "2020-10-01T20:00:00",
        "2021-03-01T21:59:59.999"
      ],
      "granularity": "day"
    }
  ],
  "limit": 5000
}
```

Results for the `day` granularity:
<img width="1223" alt="Screenshot 2024-09-25 at 10 43 19" src="https://github.com/user-attachments/assets/39f70d9c-f6a8-4e5c-8653-1854a0afcad4">

Results for the `month` granularity:
<img width="1216" alt="Screenshot 2024-09-25 at 10 43 25" src="https://github.com/user-attachments/assets/696565ac-990a-4999-b3c0-9c5e17d98362">

---

I hope this explains that this is not a bug. WDYT?
