### ISSUE TITLE
No way to disable defaultOrder

### ISSUE THREAD

**Issue by ifokeev** [cube-js/cube#250]
**Describe the bug**
There is no way to disable defaultOrder and it's not a controlled behaviour. I do machine learning  with cubejs and the score is relative to the dataset order. Now I have to hack order and place undefined dimension as the key `{'emptyCube.emptyKey': 'asc'}` and `orderHashToString` will skip it https://github.com/cube-js/cube.js/blob/1a8260522a234ebaabb9360f58e9b62095fd87f7/packages/cubejs-schema-compiler/adapter/BaseQuery.js#L799

**Expected behavior**
Allow to pass `null` with `order` in api-gateway https://github.com/cube-js/cube.js/blob/1a8260522a234ebaabb9360f58e9b62095fd87f7/packages/cubejs-api-gateway/index.js#L130

**Comment by paveltiunov** [comment]
@ifokeev Hey Ivan! What DB do you use? By data set order do you mean order of cube's sql?

**Comment by ifokeev** [comment]
> Hey Ivan! What DB do you use?

PostgreSQL, but the case doesn't lean on the database type.

> By data set order do you mean order of cube's sql?

Yes

**Comment by paveltiunov** [comment]
@ifokeev Makes sense. The thing here is most of SQL backends can't guarantee order of rows if `ORDER BY` is unspecified. Postgres doesn't provide this guarantee in general as well: https://www.postgresql.org/docs/9.5/queries-order.html. 

I think we can consider supporting passing empty `{}` order object to override default sorting behavior with a warning that resulting row order is unreliable. It can change over time due to SQL engine updates or Cube.js SQL generation changes.

**Comment by ifokeev** [comment]
@paveltiunov 
> I think we can consider supporting passing empty {} order object to override default sorting behavior

yeah, that's what I need, `defaultOrder` will become the controlled option.
