### ISSUE TITLE
Epic: Provide connectors for BI tools

### ISSUE THREAD

**Issue by rpaik** [cube-js/cube#3528]
Provide SQL connectors for leading BI tools. 

Work items include: 

- [x] Start with a connector for Superset
- [x] Prioritize other BI tools based on community feedback

**Comment by abhischekt** [comment]
We'd love to see support for a Tableau connector

**Comment by benjamine** [comment]
Google DataStudio?

**Comment by AndreasTA-AW** [comment]
The SQL API looks really promising! I'm currently looking at different metric stores and this sounds promising. We are also using DBT and I saw that you had an issue to support DBT Metrics as well.

One question, if it's supposed to be a MySQL interface, why is it necessary to implement specific BI Tools? Is it because they all use some different specifics from the interface? So eventually the SQL API will be far enough to support most of them? I tried to use DBeaver to connect, but that fails to get the columns. 
Guess I just wanted to know the reason why it's not possible to follow the MySQL spec instead of pushing in Tool by Tool :)

**Comment by paveltiunov** [comment]
Hey @AndreasTA-AW ! It's a great question. It's indeed at the first sight we should be having the support of all tools once we implement it for the first one. The reality is we actually trying to mimic a subset of MySQL protocol, introspection queries, and SQL to pretend a MySQL database for BI tools being OLAP querying engine. And while we can do protocol and introspection mostly by spec, the SQL part is the hardest one as we need to project every possible SQL BI can generate to the Cube query. As we add more tools it's fewer new queries to support but still, it's iterative.
