### ISSUE TITLE
[bug] SQL generation issues with rollingWindow and Calculated Measures

### ISSUE THREAD

**Issue by zpencerq** [cube-js/cube#3561]
**Describe the bug**
When querying a calculated measure that references a `rollingWindow` measure, the field is completely missing from result data (though it is listed in the query information as a selected measure).
There's some other oddities related to it where the referenced measure is inferred as a shown: false field even when it isn't if the calculated measure is selected alone.

**To Reproduce**
Made example here with included sqlite db: https://github.com/zpencerq/cubejs-sample
Just run `yarn dev` and select time of:

```
Users Day
Last 30 days by Week
```

Then try:

- Query 1 - `Users Predicted Monthly Activations`
  - Causes requested hidden member error despite no such configuration
- Query 2 - `Users Predicted Monthly Activations, Users Activations in Past12 Months`
  - Causes result set to have no key/value for `Users Predicted Monthly Activations` (inspecting response has no keys at all for this field)
- Query 3 - `Users Predicted Monthly Activations, Users Activations in Past12 Months, Users New Inbound Count2`
  - Causes no such column error (the count field is not used in the calculation; presumably would have same error as above)
- Query 4 -  `Users Predicted Monthly Activations, Users Activations in Past12 Months, Users New Inbound Count`
  - Works properly with all available fields included in the query

**Expected behavior**
Each of the above configurations to work without issue.

**Version:**
0.28.44

**Additional context**
Talked about in https://cube-js.slack.com/archives/CC0403RRR/p1634172906328000

**Comment by igorlukanin** [comment]
I was able to run the code from the repository on the latest (v0.36.2) version of Cube with a very minimalistic Docker Compose file:

```yaml
services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 15432:15432
      - 3306:3306
    environment:
      - CUBEJS_DEV_MODE=true
    volumes:
      - .:/cube/conf
```

The only other thing I did is renaming `schema` folder to `model`.

Apparently, the data model wasn't correct. I has to make changes to three `sql` fields' definitions:
<img width="625" alt="Screenshot 2024-09-25 at 16 42 03" src="https://github.com/user-attachments/assets/b227c164-63b0-4af0-b1f3-01a97d73af60">

With these changes, Cube generated correct SQL for all measures:
<img width="1222" alt="Screenshot 2024-09-25 at 16 19 26" src="https://github.com/user-attachments/assets/35e37141-24c4-4d97-9955-c1d9aef39879">

I believe it means that the issue is resolved now.
