### ISSUE TITLE
Upgrading to typescript 4.8 makes tsc fail due to invalid cube types

### ISSUE THREAD

**Issue by sacummings91** [cube-js/cube#5446]
Some changes in typescript from 4.7 -> 4.8 are causing tsc to fail for some types within the cubejs-client/core project. This is blocking us from upgrading typescript to the latest version.

```
node_modules/@cubejs-client/core/index.d.ts:818:31 - error TS2344: Type 'First' does not satisfy the constraint 'DeeplyReadonly<Query>'.

818       ? SingleQueryRecordType<First> | QueryArrayRecordType<Rest & DeeplyReadonly<Query[]>>
                                  ~~~~~

  node_modules/@cubejs-client/core/index.d.ts:817:31
    817     T extends readonly [infer First, ...infer Rest]
                                      ~~~~~
    This type parameter might need an `extends DeeplyReadonly<Query>` constraint.


Found 1 error in node_modules/@cubejs-client/core/index.d.ts:818
```

1. upgrade to typescript 4.8 
2. run tsc
3. Should see error reported

**Comment by buntarb** [comment]
Hey, @sacummings91. Thanks for the report. We appreciate it. However, our current typescript version is ~4.1.5, and 4.8 is not officially supported. It would be great if you would fix an issue and send us a PR with the fix.

**Comment by sacummings91** [comment]
Hey @buntarb, Just want to confirm that its understood that I am not trying to upgrade typescript in your cube repo. I am trying to upgrade typescript in my own project and its causing tsc to fail in my node_modules for cube.

If so, then yeah I can try to fix it for you guys. Is there a preferred way of contributing to cube projects? Or should I just clone it and cut a branch with the fix and push up a PR?

**Comment by buntarb** [comment]
@sacummings91, as far as I understood, some of our existing types don't work for the 4.8. But as long as we stay on 4.1, we can live with it. Right now, we don't plan to upgrade the TS version because it can cause massive refactoring (we are using monorepo). However, if you will fix these certain types from your site in a way it continues to work with both 4.1 and 4.8, we will merge your PR with pleasure.
Here is some basic stuff about contributing to the project: https://github.com/cube-js/cube.js/blob/master/CONTRIBUTING.md

**Comment by sacummings91** [comment]
Hey @buntarb, I believe I've fixed the issue but I'm running into a blocker. I'm trying to push up a PR and getting a permissions issue. Any ideas what might be going wrong here? 
![image](https://user-images.githubusercontent.com/29286028/198737483-9312a1e7-c299-4080-8294-a02a3aa23cdf.png)
