### ISSUE TITLE
Epic: Orchestration API

### ISSUE THREAD

**Issue by rpaik** [cube-js/cube#6129]
The goal is to launch the Orchestration API with support for workflow management tools. 

We will start with Prefect and Airflow support. Community feedback on other tools is welcomed 😊

**Comment by siamak-haschemi** [comment]
We would love to have an (HTTP) API to push partitions to be re-calculated to Cube, since we have in our pipeline (DBT) the exact historic days which need to be re-calculated. I would love be able to (indirectly) interact with the refresh-worker to send a list of partitions to refresh, if possible. That way, Cube would be part of our data-pipeline, instead of being isolated and polling information to reconstruct data (which days to refresh) which we already have.

See also https://cube-js.slack.com/archives/C0206EXEVAS/p1679644658432559

**Comment by igorlukanin** [comment]
Orchestration API was introduced to Cube some time ago: https://cube.dev/blog/introducing-orchestration-api

Docs: https://cube.dev/docs/product/apis-integrations/orchestration-api
