### ISSUE TITLE
Gsheet Add-On for Cube

### ISSUE THREAD

**Issue by chaos87** [cube-js/cube#6387]
A lot of Cube users would like to be able to use Cube from within Gsheets

The idea is to be able to design, edit, save and run a query as well as get the resultset inside of a chosen tab of your currently opened Google spreadsheet.

The solution could be a workspace add-on that users could install on their Google account/Gsuite workspace environment
https://developers.google.com/apps-script/add-ons/editors/sheets

(Note that we could make the add-on easily findable on [Google Workspace Marketplace](https://workspace.google.com/marketplace))

This ticket should help get requirements for such a functionality to work.

**Comment by paveltiunov** [comment]
@chaos87 It's on our roadmap. As a workaround, https://skyvia.com/ can be used to get data out of Cube using SQL API.

**Comment by igorlukanin** [comment]
Marking this issue as resolved since "Cube Cloud for Sheets" is not available so that one can bring data from Cube Cloud to G Sheets. Please see the [documentation](https://cube.dev/blog/how-to-connect-google-sheets-to-your-metrics-in-cube-cloud) and the [announcement](https://cube.dev/blog/how-to-connect-google-sheets-to-your-metrics-in-cube-cloud) in the blog.
