### ISSUE TITLE
Support Dynamodb in addition to Redis as a Cache server

### ISSUE THREAD

**Issue by gauravlanjekar** [cube-js/cube#663]
**Is your feature request related to a problem? Please describe.**
Currently only redis is supported as the cache server. Dynamodb is available at a much cheaper price than redis and would help to reduce the overall cost of the deployment.

**Describe the solution you'd like**
Support Dynamodb as additional cache server.

**Comment by paveltiunov** [comment]
@gauravlanjekar Thanks for posting this! I think it makes sense to support it. We need to check one thing though: if DynamoDB is capable of providing serialized read/write capabilities. Redis is used also to store query queue which requires this sort of capabilities.

**Comment by Ankcorn** [comment]
By serialized do you mean the storing and serializing arrays and objects? Dynamodb does support this

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html

I would be happy to take a look at this.

Would the right place to start be to create DynamoDB queue driver with the same interface as https://github.com/cube-js/cube.js/blob/7b62c1d8c8e5ee74118eac467bacffb83c6fcb3e/packages/cubejs-query-orchestrator/orchestrator/RedisQueueDriver.js#L5

**Comment by paveltiunov** [comment]
@Ankcorn Hey Thomas! I mean serializable transaction isolation. Basically we need to ensure https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/transactions.html is suitable to implement Cube.js query queue driver.

**Comment by Ankcorn** [comment]
What purpose does the transaction serve? I see there are the blocking get results methods in the redis driver. Strugling to visualise exactly what this is doing because im not that familiar with redis's methods beond a simple cache use case.

The key structure of the current solution makes me think that it would map well to a single dynamodb table with few changes.

The bits I think I would strungle to implement in the same way are where operations like rpush and lpop are used where dynamodb does not have an equivelent. If there was some documentation describing what they did then I am sure we could come up with a data structure in dynamodb that achieves the same results

**Comment by paveltiunov** [comment]
@Ankcorn So Redis is used to sync queue and deliver results. It's used as a mutually exclusive lock implementation as well as a way to push results delivery instantly as those are available instead of polling for them.

@Ankcorn I'm curious what are main points of using DynamoDB instead of Redis besides pricing? Maybe you want to implement it for cache and leave queue in Redis?

**Comment by Ankcorn** [comment]
Appologies for the radio silence

> @Ankcorn So Redis is used to sync queue and deliver results. It's used as a mutually exclusive lock implementation as well as a way to push results delivery instantly as those are available instead of polling for them.

Sounds like dynamodb wouldn't be able to fulfill the role redis does that effectively in terms of the queue. There are some options like dynamodb streams to push the results on completion, and other things but would never be as fast and flexible as redis.

> @Ankcorn I'm curious what are main points of using DynamoDB instead of Redis besides pricing? Maybe you want to implement it for cache and leave queue in Redis?

We would like to cache certain queries for ever. Queries like top y of december 2019 for customer x

**Comment by hassankhan** [comment]
Hi, just wanted to add my 2p, it does seem like [DynamoDB supports transactions](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/transactions.html).

**Comment by paveltiunov** [comment]
@Ankcorn I see. For durable cache you should use https://cube.dev/docs/pre-aggregations#top instead. Redis cache is to handle database bursts basically.

**Comment by Ankcorn** [comment]
That makes total sense, I will do some research and give it a go! 

Thank you

**Comment by Ankcorn** [comment]
Okay that's dope. Love this project <3

**Comment by abronin** [comment]
@Ankcorn do you finally work on this?

**Comment by Ankcorn** [comment]
No my use case ended up being solved with pre aggregstions

**Comment by bandaot** [comment]
Finally no one is working on it？For me, I just want a pure serverless solution, but the redis seems the only exception for now.

**Comment by hobojoe** [comment]
No plans on this? Thanks!

**Comment by rpaik** [comment]
👋 a quick reminder that we will be replacing Redis with Cube Store as announced in this [blog post](https://cube.dev/blog/replacing-redis-with-cube-store).

**Comment by igorlukanin** [comment]
I believe that this issue is not relevant anymore since Cube Store has replaced Redis for query queue and cache management.

Docs: https://cube.dev/docs/product/deployment#redis

Announcement: https://cube.dev/blog/how-you-win-by-using-cube-store-part-1
