### ISSUE TITLE
BigQuery: no matching signature error for calculated measures on `count_distinct_approx` measures

### ISSUE THREAD

**Issue by prratek** [cube-js/cube#6747]
**Describe the bug**
When defining a calculated measure in Cube that divides two measures of type `count_distinct_approx`, Cube generates invalid SQL. It attempts to divide two HLL sketches, which are of type `BYTES`, which results in this error:
```
No matching signature for operator / for argument types: BYTES, BYTES
```

**To Reproduce**
See the minimally reproducible schema below. When Cube attempts to generate a pre-aggregation you should see the error above.

**Expected behavior**
Current Query:
```sql
SELECT
  `my_cube`.my_dimension `my_cube__my_dimension`, 
  HLL_COUNT.INIT(CASE WHEN (`my_cube`.viewed) THEN `my_cube`.user_id END) / HLL_COUNT.INIT(`my_cube`.user_id) `my_cube__ctr`
FROM
    (
  SELECT * 
  FROM my_table
)  
GROUP BY 1, 2
```

Expected Query:
```sql
SELECT
  `my_cube`.my_dimension `my_cube__my_dimension`, 
  HLL_COUNT.EXTRACT(HLL_COUNT.INIT(CASE WHEN (`my_cube`.viewed) THEN `my_cube`.user_id END)) /
    HLL_COUNT.EXTRACT(HLL_COUNT.INIT(`my_cube`.user_id) ) `my_cube__ctr`
FROM
    (
  SELECT * 
  FROM my_table
)  
GROUP BY 1, 2
```

**Screenshots**

**Minimally reproducible Cube Schema**
In case your bug report is data modeling related please put your minimally reproducible Cube Schema here.
You can use selects without tables in order to achieve that as follows.

```javascript
cube(`my_cube`, {
  sql: `
  select * from my_table
  `,
  measures: {
    clicks: {
      sql: `user_id`,
      type: `count_distinct_approx`,
      filters: [{ sql: `${CUBE.clicked}` }]
    },
    views: {
      sql: `user_id`,
      type: `count_distinct_approx`,
      filters: [{ sql: `${CUBE.viewed}` }]
    },
    ctr: {
      sql: `${clicks} / ${views}`,
      type: `number`
    },
  },
  dimensions: {
    my_dimension: {
      sql: `my_dimension`,
      type: `string`,
    },
  },
});
```

**Version:**
0.33.28

**Additional context**

**Comment by igorlukanin** [comment]
Hi @prratek 👋 

I think this is not actually a bug, it's a misconfiguration. Long story short, `ctr` should not be used in a pre-aggregation. Instead, `clicks` and `views` should. This is because `ctr` is. calculated measure. Cube Store can calculate it on-the-fly based on `clicks` and `views` and this is why they should be added in a pre-aggregation instead. 

Please take a look at the following data model:
```js
cube(`my_cube`, {
  sql: `SELECT 123 AS user_id`,

  measures: {
    clicks: {
      sql: `user_id`,
      type: `count_distinct_approx`
    },

    views: {
      sql: `user_id`,
      type: `count_distinct_approx`
    },
    
    ctr: {
      sql: `${clicks} / ${views}`,
      type: `number`
    },

    // This measure is added to work around this bug only:
    // https://github.com/cube-js/cube/issues/8916$0
    count: {
      type: `count`
    }
  },

  pre_aggregations: {
    main: {
      measures: [
        clicks,
        views,
        count,
        // ctr
      ]
    }
  }
})
```

With this data model, if you run a query with `ctr`, it will work flawlessly:
<img width="1219" alt="Screenshot 2024-11-06 at 12 52 52" src="https://github.com/user-attachments/assets/a819fa77-3b6b-4902-bede-fb775a18d10a">

Correct SQL is generated as well:
<img width="1220" alt="Screenshot 2024-11-06 at 12 53 01" src="https://github.com/user-attachments/assets/a84ec654-3441-4612-a341-6fdcee071208">

However, if you remove the comment on `ctr` in the pre-aggregation definition, you will get the error is shown above.

I hope this helps!
