### ISSUE TITLE
Compile context for controlling access to cubes

### ISSUE THREAD

**Issue by ViktoriyaBurdey** [cube-js/cube#6974]
**Problem**

We want to use COMPILE_CONTEXT for controlling access to cubes, measures, dimensions etc, how it's described [here](https://cube.dev/docs/guides/recipes/access-control/controlling-access-to-cubes-and-views). We have roles in compile context depending on user token. And it's working after compile cube. However, we found that when changing the role in the user token or changing the user itself, the compile context remains unchanged until cube-api is overloaded. Because of this, there is no possibility to restrict access to the cube depending on the user. 

Can you please tell me if this is normal behavior or we have some kind of error?

**Related Cube.js schema**
```javascript
measures: {
    count: {
      type: `count`,
      sql: `distinct ${CUBE}."id"`,
      public: COMPILE_CONTEXT.isAdmin
    },
  },
```

**Cube options**
```
extendContext: {
    isAdmin: securityContext.roles.includes("admin")
}
```

**Cube version**
0.33.29

**Comment by keydunov** [comment]
This issue happens when `contextToAppId` is not defined. `contextToAppId` tells Cube when to recompile your schema (data model). Think about it as a mapping of many (security contexts) to one (compile context). When it is undefined, Cube thinks that all your security contexts belong to the same compile context, and therefore it doesn't recompile schema (data model).
