### ISSUE TITLE
Getting Unsupported CAST while adding 1 day to timestamp coming from a cube

### ISSUE THREAD

**Issue by anshjain18** [cube-js/cube#8096]
**Failed SQL**
`select max(date_trunc('hour', time))  + (interval '1 day') from my_cube`

** Error ** 
Unsupported CAST from Interval(DayTime) to Timestamp(Nanosecond, None).

**Version:**
0.34.61

**Additional context**
1. Here my_cube is a simple cube, which has a time dimension 'time'
2. When I add interval to a static timestamp, it works just fine. Example: `select cast('2023-03-22T00:00:00' as timestamp) + (interval '1 day')`

**Comment by igorlukanin** [comment]
Hi @anshjain18 👋 

Please switch to the latest version and enable `CUBESQL_SQL_PUSH_DOWN=true`. It fixes this issue for me:
<img width="870" alt="Screenshot 2024-04-09 at 11 39 04" src="https://github.com/cube-js/cube/assets/3852894/3ca73ca3-d766-4935-b727-2d4b86f4b225">

**Comment by anshjain18** [comment]
Hey @igorlukanin, thank you so much for the quick reply. Will try this and update here if it works.

**Comment by anshjain18** [comment]
Hey @igorlukanin should I pass this env variable for Cube or Cubestore?

**Comment by anshjain18** [comment]
@igorlukanin 
1. This query worked in the new version.
2. However my other very basic query broke where I just query a metric while filtering a segment. The query is `select measure_1, date_trunc('hour', time) from cube where my_segment = true`. 
3. It was working perfectly in the previous versions and now it says "No pre-aggregation table has been built for this query".
4. Can we please check this

**Comment by igorlukanin** [comment]
> should I pass this env variable for Cube or Cubestore?
Cube

> my other very basic query broke
> now it says "No pre-aggregation table has been built for this query"
As the error message suggests, Cube can't find the pre-aggregation table, Please check that your refresh worker has built this pre-aggregation. Can you see that in the logs? Can you see the related Parquet file? Also, are both your API instances and the refresh worker successfully connected to Cube Store Router?

These are the questions that you can use to investigate.

> This query worked in the new version
I'm glad to hear that!

Since the new issue is unrelated to the SQL API, let me close this one—please feel free to raise a new one or ask on slack.cube.dev.
