### ISSUE TITLE
 Are there any hidden risks associated with not using Cubestore and opting for the memory driver instead?

### ISSUE THREAD

**Issue by w1992wishes** [cube-js/cube#8101]
**Is your feature request related to a problem? Please describe.**

Hello, I'd like to inquire about the potential issues and hidden risks associated with using CubeJS without Cubestore, enabling memory mode with CUBEJS_CACHE_AND_QUEUE_DRIVER=memory, setting CUBEJS_DEV_MODE=false, and not configuring CUBEJS_CUBESTORE_HOST. Could you please provide insights into the potential drawbacks and risks of this usage pattern?

**Comment by igorlukanin** [comment]
Hi @w1992wishes 👋 

In this setup, the only API instance would also manage the query queue in its in-memory Cube Store. You will not be able to add a refresh worker instance because it coordinates its work via the query queue. Same is true for adding any Cube Store Worker instances. You also risk getting out-of-memory errors and generally a potential instability because the query queue and in-memory cache are co-located with the API instance.

Such a setup is not considered stable and reliable enough for production purposes and it has no horizontal scalability; you can only scale it vertically by allocating more memory and CPU.

**Comment by w1992wishes** [comment]
I understand, thank you. I will take it into consideration.
